use INMETRO
go
-- #### Inserir linhas de backup novamente nas tabelas principais ####

-- ####
insert CONTROLEACESSO.TB_LOGIN (
CDA_LOGIN,
NOM_PESSOA_FISICA,
DES_EMAIL,
IDT_PESSOA_FISICA,
BLN_CONTROLE_EXCLUIDO,
CDA_CONTROLE_ORIGEM,
DAT_CONTROLE_ALTERACAO
)
select
CDA_LOGIN,
NOM_PESSOA_FISICA,
DES_EMAIL,
IDT_PESSOA_FISICA,
BLN_CONTROLE_EXCLUIDO,
CDA_CONTROLE_ORIGEM,
DAT_CONTROLE_ALTERACAO
from CONTROLEACESSO.BKP_TB_LOGIN


-- ####
insert CONTROLEACESSO.TB_LOGIN_EXTERNO (
CDA_LOGIN_EXTERNO,
IDT_PESSOA_FISICA,
DES_EMAIL,
BLN_CONTROLE_EXCLUIDO,
CDA_CONTROLE_ORIGEM,
DAT_CONTROLE_ALTERACAO
)
select
CDA_LOGIN_EXTERNO,
IDT_PESSOA_FISICA,
DES_EMAIL,
BLN_CONTROLE_EXCLUIDO,
CDA_CONTROLE_ORIGEM,
DAT_CONTROLE_ALTERACAO
from CONTROLEACESSO.BKP_TB_LOGIN_EXTERNO


-- ####
insert CONTROLEACESSO.TB_LOGIN_EXTERNO_SENHA (
IDT_LOGIN_EXTERNO,
DES_SENHA,
DAT_EXPIRACAO_SENHA,
CDA_TIPO_SENHA,
BLN_CONTROLE_EXCLUIDO,
CDA_CONTROLE_ORIGEM,
DAT_CONTROLE_ALTERACAO
)
select 
L.IDT_LOGIN_EXTERNO,
B.DES_SENHA,
B.DAT_EXPIRACAO_SENHA,
B.CDA_TIPO_SENHA,
B.BLN_CONTROLE_EXCLUIDO,
B.CDA_CONTROLE_ORIGEM,
B.DAT_CONTROLE_ALTERACAO
from CONTROLEACESSO.BKP_TB_LOGIN_EXTERNO_SENHA B join
     CONTROLEACESSO.TB_LOGIN_EXTERNO L on
          L.CDA_LOGIN_EXTERNO = B.CDA_LOGIN_EXTERNO

-- ####
insert CONTROLEACESSO.TB_LOGIN_EXTERNO_SISTEMA_PERFIL (
IDT_LOGIN_EXTERNO,
IDT_SISTEMA,
IDT_PERFIL,
BLN_CONTROLE_EXCLUIDO,
CDA_CONTROLE_ORIGEM,
DAT_CONTROLE_ALTERACAO
)
select 
L.IDT_LOGIN_EXTERNO,
B.IDT_SISTEMA,
B.IDT_PERFIL,
B.BLN_CONTROLE_EXCLUIDO,
B.CDA_CONTROLE_ORIGEM,
B.DAT_CONTROLE_ALTERACAO
from CONTROLEACESSO.BKP_TB_LOGIN_EXTERNO_SISTEMA_PERFIL B join
     CONTROLEACESSO.TB_LOGIN_EXTERNO L on
          L.CDA_LOGIN_EXTERNO = B.CDA_LOGIN_EXTERNO

-- ####
insert CONTROLEACESSO.TB_LOGIN_SISTEMA_PERFIL (
IDT_LOGIN,
IDT_SISTEMA,
IDT_PERFIL,
BLN_CONTROLE_EXCLUIDO,
CDA_CONTROLE_ORIGEM,
DAT_CONTROLE_ALTERACAO
)
select
L.IDT_LOGIN,
B.IDT_SISTEMA,
B.IDT_PERFIL,
B.BLN_CONTROLE_EXCLUIDO,
B.CDA_CONTROLE_ORIGEM,
B.DAT_CONTROLE_ALTERACAO
from CONTROLEACESSO.BKP_TB_LOGIN_SISTEMA_PERFIL B join
     CONTROLEACESSO.TB_LOGIN L on
          L.CDA_LOGIN = B.CDA_LOGIN